image:
  # tag: "v3.6.8"
  tag: "v3.7.0-ea.1"
  pullPolicy: Always
deployment:
  replicas: 2
ingressRoute:
  dashboard:
    enabled: false
ingressClass:
  enabled: false
providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
    allowEmptyServices: true
  kubernetesIngress:
    enabled: true
    ingressClass: "traefik"
  # kubernetesIngressNGINX:
  kubernetesIngressNginx:
    enabled: true
    ingressClass: "tmp-nginx"
    # controllerClass: "k8s.io/ingress-tmp-nginx"
    # watchIngressWithoutClass: false
    ingressClassByName: true
    publishService:
      enabled: true
    # allowSnippetAnnotations: true
logs:
  general:
    format: json
    level: DEBUG
  access:
    enabled: true
    format: json
    addInternals: false
    fields:
      general:
        defaultmode: keep
      headers:
        defaultmode: keep
resources:
  requests:
    memory: 384Mi
    cpu: 200m
  limits:
    memory: 384Mi
    cpu: 200m
ports:
  websecure:
    http:
      tls:
        enabled: true
additionalArguments:
  - "--api.insecure=true"